# https://github.com/edbizarro/gitlab-ci-pipeline-php
image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine

stages:
  - build
  - test
  - metrics

variables:
  REPORT_DIR: "reports"
  PHPMETRICS: "v2.4.1"
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - vendor
    - web
    - composer.lock

.ensure_report:
  - &ensure_report
    mkdir -p ${REPORT_DIR} && chmod -R 777 ${REPORT_DIR}

.default_artifacts: &default_artifacts
  paths:
    - ${REPORT_DIR}/*.html
  name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
  expire_in: 1 day
  when: always

.test_template: &test_template
  dependencies:
    - build
  before_script:
    - mkdir -p ${REPORT_DIR}/coverage-xml
    - mkdir -p ${REPORT_DIR}/coverage-html
    - *ensure_report
    #- composer install --prefer-dist --no-ansi --no-interaction --no-progress --quiet --profile
    #- composer --verbose install-boostrap-sass
  script:
    - cd ${CI_PROJECT_DIR}/web
    - ${CI_PROJECT_DIR}/vendor/bin/drush site-install --verbose --yes config_installer config_installer_sync_configure_form.sync_directory="../config/sync" --db-url=${SIMPLETEST_DB}
    - ${CI_PROJECT_DIR}/vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
    - until curl -s $SIMPLETEST_BASE_URL; do sleep 5s; done > /dev/null
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
  # Ignore Setup group temporarily, @see https://www.drupal.org/node/2962157
    - ${CI_PROJECT_DIR}/vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache,Setup --coverage-text --colors=never
    - ${CI_PROJECT_DIR}/vendor/bin/drush status > ../${REPORT_DIR}/drush.txt
    - ${CI_PROJECT_DIR}/vendor/bin/drupal site:status > ../${REPORT_DIR}/console.txt
  # https://docs.gitlab.com/ee/ci/yaml/#coverage
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    <<: *default_artifacts
    paths:
      - ${REPORT_DIR}/*

build:
  stage: build
  script:
    - composer --verbose --no-check-all --no-check-publish validate
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --quiet --profile
    - composer --verbose install-boostrap-sass

.test Php 7.1:
  stage: test
  image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine
  <<: *test_template

test Php 7.2:
  stage: test
  <<: *test_template

security report:
  stage: test
  dependencies:
    - build
  before_script:
    - if [ ! -f ./security-checker ];
      then
        curl -fsSL https://get.sensiolabs.org/security-checker.phar -o security-checker;
      fi
    - chmod +x security-checker
    - *ensure_report
  script:
    - ./security-checker security:check
    - ./security-checker security:check > ${REPORT_DIR}/security.txt
  artifacts:
    <<: *default_artifacts
    paths:
      - ${REPORT_DIR}/security.txt
  cache:
    paths:
      - security-checker

metrics:
  stage: metrics
  dependencies:
    - build
  before_script:
    - if [ ! -f ./phpmetrics ];
      then
        curl -fsSL https://github.com/phpmetrics/PhpMetrics/releases/download/${PHPMETRICS}/phpmetrics.phar -o phpmetrics;
      fi
    - chmod +x phpmetrics
    - *ensure_report
  script:
    - ./phpmetrics
        --report-html=${REPORT_DIR}
        --extensions=php,inc,module
        web
  artifacts:
    <<: *default_artifacts
  cache:
    paths:
      - phpmetrics