# https://github.com/edbizarro/gitlab-ci-pipeline-php
image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine

stages:
  - build
  - test
  - metrics

variables:
  REPORT_DIR: "reports"
  PHPMETRICS: "v2.4.1"

cache:
  key: drupal-project-$CI_BUILD_REF_NAME
  paths:
    - vendor
    - web
    - load.environment.php
    - composer.json
    - composer.lock
    - ./*.phar

.ensure_report:
  - &ensure_report
    mkdir -p ${REPORT_DIR} && chmod -R 777 ${REPORT_DIR}

.default_artifacts: &default_artifacts
  paths:
    - ${REPORT_DIR}/*.html
  name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
  expire_in: 1 day
  when: always

.report_template: &report_template
  dependencies:
    - build
  before_script:
    - if [ ! -f ./${TOOL_PHAR} ];
      then
        curl -fsSL ${TOOL_URL} -o ${TOOL_PHAR};
      fi
    - chmod +x ${TOOL_PHAR}
    - *ensure_report
  artifacts:
    <<: *default_artifacts
    paths:
      - ${REPORT_DIR}/*

build:
  stage: build
  script:
    - composer --verbose --no-check-all --no-check-publish validate
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --profile
    - composer --verbose install-boostrap-sass
  artifacts:
    <<: *default_artifacts
    paths:
      - vendor
      - web
      - load.environment.php
      - composer.json
      - composer.lock

test:
  stage: test
  image: mogtofu33/drupal8ci:8.6
  services:
    - mariadb:latest
  dependencies:
    - build
  before_script:
    - cp .gitlab-ci/phpunit.xml web/core/
    - mkdir -p /var/www/html
    - ln -s $CI_PROJECT_DIR/web /var/www/html/web
    # Prepare tests folder.
    - mkdir -p "${BROWSERTEST_OUTPUT_DIRECTORY}"
    - chmod -R g+s "${BROWSERTEST_OUTPUT_DIRECTORY}"
    - chown -R www-data:www-data "${BROWSERTEST_OUTPUT_DIRECTORY}"
    - apache2-foreground&
    - mkdir -p ${REPORT_DIR}/coverage-html
    - *ensure_report
  script:
    - cp .gitlab-ci/settings-ci.php web/sites/default/settings.php
    - mkdir -p web/sites/default/files
    - cd ${CI_PROJECT_DIR}/web
    - ${CI_PROJECT_DIR}/vendor/bin/drush site-install --yes config_installer config_installer_sync_configure_form.sync_directory="../config/sync" --db-url=${SIMPLETEST_DB}
    - ${CI_PROJECT_DIR}/vendor/bin/drush status --field=bootstrap
    # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
    # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
    # Ignore Setup group temporarily, @see https://www.drupal.org/node/2962157
    - sudo -E -u www-data
      ${CI_PROJECT_DIR}/vendor/bin/phpunit
        -c ${CI_PROJECT_DIR}/web/core
        --verbose
        --exclude-group Composer,DependencyInjection,PageCache,Setup
        --coverage-text --colors=never
        --testsuite unit
  variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    MYSQL_DATABASE: "drupal"
    SIMPLETEST_DB: "mysql://root@mariadb/drupal"
    SIMPLETEST_BASE_URL: "http://localhost"
    BROWSERTEST_OUTPUT_DIRECTORY: "/var/www/html/web/sites/simpletest"
  #artifacts:
  #  <<: *default_artifacts
  #  paths:
  #    - ${REPORT_DIR}/*.html
  #    - ${REPORT_DIR}/coverage-html/*
  # https://docs.gitlab.com/ee/ci/yaml/#coverage
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  allow_failure: true

security report:
  stage: test
  <<: *report_template
  script:
    - ./${TOOL_PHAR} security:check
  variables:
    TOOL_PHAR: "security-checker.phar"
    TOOL_URL: "https://get.sensiolabs.org/security-checker.phar"

metrics:
  stage: metrics
  <<: *report_template
  script:
    - ./${TOOL_PHAR}
        --report-html=${REPORT_DIR}
        --extensions=php,inc,module,theme
        web
  variables:
    TOOL_PHAR: "phpmetrics.phar"
    TOOL_URL: "https://github.com/phpmetrics/PhpMetrics/releases/download/${PHPMETRICS}/phpmetrics.phar"
  artifacts:
    <<: *default_artifacts
  when: manual
