################################################################################
# Gitlab CI integration for Drupal 8/9 project or module: tests, code quality,
# linting, metrics and deploy samples.
#
# Project: https://gitlab.com/mog33/gitlab-ci-drupal
# Documentation: https://mog33.gitlab.io/gitlab-ci-drupal
# Issues: https://gitlab.com/mog33/gitlab-ci-drupal/-/issues
# Author: Jean Valverde contact@dev-drupal.com
# License: GPL-3
#
# If you want to support this project, you can
# - Buy me a coffee: https://bit.ly/34jPKcE
# - Hire me as a freelance for any Drupal related work
# - Promote me to any company looking for any Drupal related work
# - Help me with testing / documentation / grammar fixes / use cases
#
################################################################################

include:
  - project: 'mog33/gitlab-ci-drupal'
    ref: 2.x-dev
    file: '/.gitlab-ci/.gitlab-ci-template.yml'

variables:
  extends: .default_variables
  CI_REF: 2.x-dev
  DIRS_QA: "${WEB_ROOT}/modules/contrib/content_moderation_edit_notify"
  DIRS_JS: "${CI_PROJECT_DIR}/**/modules/contrib/content_moderation_edit_notify/js/*.js"
  DIRS_TWIG: "${WEB_ROOT}/core/modules/block/templates"
  DIRS_PHP: "${WEB_ROOT}/modules/contrib/content_moderation_edit_notify"
  SKIP_TEST_BEHAT: 1
  SKIP_TEST_PA11Y: 1
  SKIP_TEST_NIGHTWATCH: 1
  SKIP_TEST_UNITKERNEL: 1
  SKIP_TEST_FUNCTIONAL: 1
  SKIP_TEST_FUNCTIONALJS: 1
  SKIP_LINT_CSS: 1
  #TOOLS_QA: "phpcs:0,phpstan:0,phpmd:0,phpcpd:0"

stages:
  - build
  - tests
  - metrics
  - reports

pages:
  stage: reports
  extends: .simple_dashboard
  rules:
    - when: always
