language: php
dist: bionic
sudo: false

php:
  - 7.2
  - 7.3

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
    - COMPOSER_MEMORY_LIMIT=-1
    - PHPUNIT_TESTS=custom

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --stable
  - composer --version
  - cp $TRAVIS_BUILD_DIR/.gitlab-ci/RoboFile.php $TRAVIS_BUILD_DIR
  - composer global require consolidation/robo
  - echo $COMPOSER_BIN_DIR

install:
  - /home/travis/.config/composer/vendor/bin/robo project:build
  - /home/travis/.config/composer/vendor/bin/robo yarn:install
  - /home/travis/.config/composer/vendor/bin/robo install:phpunit

script:
  - cd $TRAVIS_BUILD_DIR/web
  - $TRAVIS_BUILD_DIR/vendor/bin/drush -y si --existing-config --account-name=admin --account-pass=password --db-url=$SIMPLETEST_DB
  - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do sleep 2s; done > /dev/null
  - $TRAVIS_BUILD_DIR/vendor/bin/drupal site:status
  - cd $TRAVIS_BUILD_DIR
  - /home/travis/.config/composer/vendor/bin/robo test:suite "${PHPUNIT_TESTS}unit,${PHPUNIT_TESTS}kernel"
