language: php
dist: bionic
sudo: false

php:
  - 7.2
  - 7.3

env:
  global:
    - VERBOSE=1
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
    - COMPOSER_MEMORY_LIMIT=-1
    - PHPUNIT_TESTS=custom
    - CI_TYPE=project
    - CI_DRUPAL_VERSION=8.7
    - TOOLS=phpcs:0,phpmd
    - BEST_PRACTICES=phpcs:0
    - CI_PROJECT_DIR=$TRAVIS_BUILD_DIR
    - DOC_ROOT=$TRAVIS_BUILD_DIR
    - WEB_ROOT=$TRAVIS_BUILD_DIR/web
    - REPORT_DIR=reports
    - COMPOSER_BIN_DIR=/home/travis/.config/composer/vendor/bin

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --stable
  - composer --version
  - curl -f -N https://gitlab.com/mog33/drupal8ci/raw/master/8.x/drupal/composer.json -o /home/travis/.config/composer/composer.json
  - composer global install --no-ansi -n --profile --no-suggest
  - cp $TRAVIS_BUILD_DIR/.gitlab-ci/RoboFile.php $TRAVIS_BUILD_DIR
  # - composer global require consolidation/robo:^1 edgedesign/phpqa:^1.23 --update-no-dev

install:
  - $COMPOSER_BIN_DIR/robo project:build
  - $COMPOSER_BIN_DIR/robo yarn:install
  - $COMPOSER_BIN_DIR/robo install:phpunit
  - cp $TRAVIS_BUILD_DIR/.gitlab-ci/phpunit.xml $WEB_ROOT/core
  # - cd $TRAVIS_BUILD_DIR/web
  # - $TRAVIS_BUILD_DIR/vendor/bin/drush -y si --existing-config --db-url=$SIMPLETEST_DB
  # - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  # - until curl -s $SIMPLETEST_BASE_URL; do sleep 2s; done > /dev/null
  # - $TRAVIS_BUILD_DIR/vendor/bin/drush core:status

script:
  - cd $TRAVIS_BUILD_DIR
  # - $COMPOSER_BIN_DIR/robo test:suite "${PHPUNIT_TESTS}unit,${PHPUNIT_TESTS}kernel"
  - $COMPOSER_BIN_DIR/phpqa --tools security-checker:0
      --buildDir ${REPORT_DIR}
      --analyzedDirs ${DOC_ROOT}
      --verbose
