_core:
  default_config_hash: IQjf_ytthngZTAk_MU8-74VecArWD3G5g0oEH6PM6GA
toolbar_items:
  - devel.cache_clear
  - devel.configs_list
  - devel.container_info.service
  - devel.route_info.item
  - devel.admin_settings_link
  - devel_generate.generate2
  - devel.phpinfo
  - devel.menu_rebuild
  - devel.run_cron
  - devel.state_system_page
