toolbar_items:
  - devel.cache_clear
  - devel.configs_list
  - devel.route_info.item
  - devel.menu_rebuild
  - devel.reinstall
  - devel.route_info
  - devel.run_cron
  - devel.state_system_page
_core:
  default_config_hash: ysHEvvazIuaJ5BdY0dUw2_my_Q5hM8ypdXwFfaIrvMw
