ui:
  show:
    default_display: true
    advanced_column: true
    display_embed: true
    preview_information: true
    sql_query:
      where: above
      enabled: true
    performance_statistics: true
    additional_queries: false
  exposed_filter_any_label: new_any
  always_live_preview: false
