ui:
  show:
    additional_queries: false
    advanced_column: true
    default_display: true
    performance_statistics: true
    preview_information: true
    sql_query:
      enabled: true
      where: above
    display_embed: true
  always_live_preview: false
  exposed_filter_any_label: new_any
