_core:
  default_config_hash: l23AWlsVwlhblRhggKqahd8SBZzQDs5_GsFuCKgDItg
exclude_paths: "/admin/*\r\n/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css"
intercept_redirects: false
purge_on_cache_clear: true
active_toolbar_items:
  ajax: ajax
  assets: assets
  blocks: blocks
  cache: cache
  database: database
  devel: devel
  events: events
  forms: forms
  frontend: frontend
  http: http
  memory: memory
  request: request
  routing: routing
  services: services
  state: state
  time: time
  user: user
  views: views
  configs: '0'
  extensions: '0'
  mail: '0'
  theme: '0'
  translations: '0'
query_sort: duration
query_highlight: 5
ide: 'phpstorm://open?file=%f&line=%l'
ide_remote_path: ''
ide_local_path: ''
