purge_on_cache_clear: true
storage: profiler.database_storage
exclude: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css\r\n/admin/*"
ide_link: 'txmt://open?url=file://@file&line=@line'
ide_link_remote: ''
ide_link_local: ''
active_toolbar_items:
  assets: assets
  blocks: blocks
  cache: cache
  database: database
  devel: devel
  forms: forms
  mail: mail
  performance_timing: performance_timing
  php_config: php_config
  request: request
  routing: routing
  theme: theme
  user: user
  views: views
  config: '0'
  events: '0'
  drupal_extension: '0'
  http: '0'
  services: '0'
  state: '0'
  time: '0'
query_sort: source
query_highlight: 5
_core:
  default_config_hash: w1Hg1sJmlqc38y_J-HQH8kLDLRH3wuEhx-Fkwz7m-SI
