purge_on_cache_clear: false
storage: profiler.database_storage
exclude: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css"
active_toolbar_items:
  assets: assets
  cache: cache
  config: config
  database: database
  devel: devel
  forms: forms
  performance_timing: performance_timing
  request: request
  routing: routing
  user: user
  blocks: '0'
  events: '0'
  drupal_extension: '0'
  http: '0'
  mail: '0'
  php_config: '0'
  services: '0'
  state: '0'
  theme: '0'
  time: '0'
  views: '0'
ide_link: ''
ide_link_remote: ''
ide_link_local: ''
query_sort: duration
query_highlight: 5
